Feature - Implement login service
AsianTechInc/AT-MVVM-iOS pull request #4
Opened 2017-04-11 06:55 UTC by at-daiho

2017-04-11 07:10 UTC, at-daonguyen requested changes
@at-daiho Please check my comments.

2017-04-11 07:10 UTC, at-daonguyen commented on Demo/Library/Ext/String.swift
> +
Please remove whitespace.

2017-04-11 07:10 UTC, at-daonguyen commented on Demo/Library/Ext/String.swift
> +
Please remove whitespace.

2017-04-11 07:10 UTC, at-daonguyen commented on Demo/Model/API/UserAPIs.swift
> +
Please remove whitespace.

2017-04-11 07:10 UTC, at-daonguyen commented on Demo/Model/API/UserAPIs.swift
> +        if let base64Encode = "\(params.mail):\(params.pass)".base64Encode {
Can you separate this operation to new function?

2017-04-11 07:14 UTC, at-truongnguyen commented on Demo/Model/API/UserAPIs.swift
> +        let _ = APIManager.request(method: HTTPMethod.get, urlString: ApiPath.Users, parameters: nil, headers: headers) { (result) in
I think we already have `api`

2017-04-11 07:17 UTC, at-daiho commented on Demo/Model/API/UserAPIs.swift
> +        let _ = APIManager.request(method: HTTPMethod.get, urlString: ApiPath.Users, parameters: nil, headers: headers) { (result) in
request is static func.

2017-04-11 07:19 UTC, at-truongnguyen commented on Demo/Model/API/UserAPIs.swift
> +        let _ = APIManager.request(method: HTTPMethod.get, urlString: ApiPath.Users, parameters: nil, headers: headers) { (result) in
you could change it 👯‍♂️

2017-04-11 07:32 UTC, at-truongnguyen commented on Demo/Model/API/UserAPIs.swift
> +        let _ = api.request(method: HTTPMethod.get, urlString: ApiPath.Users, parameters: nil, headers: headers) { (result) in
@at-daiho I think we no need `let` here 👯

2017-04-13 01:52 UTC, at-daonguyen commented
@at-daiho Any update?

2017-04-13 04:33 UTC, at-daonguyen approved these changes

2017-04-13 04:33 UTC, merged